### ISSUE TITLE
没能成功下载，请问可能是什么问题

### ISSUE THREAD

**Issue by GarboYang** [lonsty/scraper#4]
目前没能成功下载过，用的是Mac的终端

一个下载显示没图片：
https://www.hellorf.com/image/contributor/1bd6bc1661018q
python crawler.py -u 念未生
https://tva1.sinaimg.cn/large/0081Kckwly1gl7g2b7txsj30vo0kaq5q.jpg

一个下载显示没有该用户
https://www.hellorf.com/image/contributor/cd9e15s72142c
python crawler.py -u Ellegant
https://tva1.sinaimg.cn/large/0081Kckwly1gl7g3spwhaj30vo0kaq5u.jpg

请教可能是什么问题呀

**Comment by lonsty** [comment]
因为此工具只能下载 站酷 https://www.zcool.com.cn/ 的作品，而你要下载的是另外一个网站 （站酷海洛 https://www.hellorf.com/）。

念未生 是这个主页 https://www.zcool.com.cn/u/1661018 ，确实没有内容。Ellegant 也不存在。
