### ISSUE TITLE
开发建议

### ISSUE THREAD

**Issue by lonsathing** [lonsty/scraper#5]
建议开发一下cun视觉 cnu.cc这个网站的爬虫，这个网站的图片质量也比较高

**Comment by lonsty** [comment]
我研究下，请关注后续更新。

**Comment by lonsty** [comment]
CNU 视觉 作品集的爬虫已经更新 6aa9ba2。

TODO：

- [x] 解决 ruia 框架下载慢的问题 https://github.com/howie6879/ruia/issues/125
- [x] 下载个人所有作品集，个人推荐作品集

**Comment by lonsathing** [comment]
亲测没有问题，不知道是不是网络问题，国外下载没有站酷快，如果能有类似站酷的用户所有作品集下载就好了，爆赞

**Comment by lonsty** [comment]
- ruia 作者很给力，框架问题已经修复，需要 ruia >= 0.8.0: `pip install -U ruia`
- 下载用户所有作品集，和用户的所有推荐作品集 功能也已完成
