### ISSUE TITLE
Win10无法安装uvloop

### ISSUE THREAD

**Issue by Jazzwind** [lonsty/scraper#9]
运行pip install -r requirements.txt时，报错uvloop不知道Windows...请问一下是系统的问题吗？（刚接触pip，谢谢！）

操作流程：
1. powershell直接输入“pip install -U zcooldl” 顺利安装各种东西
2. 将整个code下载，解压为一个“scraper-master”文件夹
3. powershell输入“cd 路径/scraper-master”
4. powershell输入“pip install -r requirements.txt” 后 报错， “RuntimeError: uvloop does not support Windows at the moment”
5. 此时，powershell输入“python cnu.py http://www.cnu.cc/users/142231”，并不能运行。请问一下有什么办法吗？谢谢！
![1](https://user-images.githubusercontent.com/62089810/116835325-849a3280-abf4-11eb-9fa2-e2aee5a991ff.png)
![2](https://user-images.githubusercontent.com/62089810/116835329-895ee680-abf4-11eb-89e8-880420b4b35b.png)

**Comment by lonsty** [comment]
你好，requirements.txt 中的 ruia 依赖了 uvloop，而 uvloop 当前不支持 Windows，作者好像也没准备支持。

你上面运行出错 :

> ModuleNotFoundError: No module named 'typer'

是因为安装 uvloop 失败导致后面的依赖没有安装。

------
**针对 Windows 的解决方法：**

把 requirements.txt 中 `ruia[uvloop]>=0.8.0` 修改为 `ruia>=0.8.0`（ruia 仍可用，但并发降低），然后 `pip install -r requirements.txt` 安装完整依赖。

**Comment by lonsty** [comment]
https://github.com/MagicStack/uvloop/issues/14 #

**Comment by lonsty** [comment]
https://github.com/MagicStack/uvloop/issues/14

**Comment by Jazzwind** [comment]
明白了，非常感谢！
使用ruia后就可以顺利安装，正常使用了。非常感谢！
